name: Docker Build & Helm Deploy

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: guardplus
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/guardplus:${{ env.IMAGE_TAG }}

  helm-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Deploy to Kubernetes via Helm
        run: |
          helm upgrade --install guardplus ./chart             --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/guardplus             --set image.tag=${{ env.IMAGE_TAG }}             --kubeconfig ${{ secrets.KUBECONFIG_CONTENT }}